language: generic
services:
- docker
env:
- DOCKER_COMPOSE_VERSION=1.23.2
jobs:
  include:
  - stage: deploy
    if: "(NOT type IN (pull_request)) AND (branch = master)"
    deploy:
      provider: heroku
      api_key:
        secure: ccsH6E1HK6C9ewP27Uaw/cNkVUulAXxKtRhEzD5phZsgx+OfKjxwDOF/LM3Ca2OQLcC4sezhJAwGyZkz475NkmRzkkLkVvwEkyo9YANGkS41T8kp3aj1CB0Hq23KsjhfvvIK88XPacGt18kEDrv2c/er3lGzFnP7S2abL7a4tLh3v23zO5QOdLIfBBoRoFv2/4IlS4abi5uewgEr74CZoxJ/Ra1Tn1dc1xvoxGYyIMqHq0jncJfw9cLZ3nTqy0nVcgvXVt+zxwaIXwjGp0h12lGEcTqKpL44vLZM/yXaYGKF3m3W1AIJrOeOtw5l4OaPMfoPOwMB6zh0t0rwIZU24KYpWCeNmFGYzZSxBcXEIQS8AT+FNaW5bILCwZypZWXy/KbOK9xs66AT7xLImjZurR/Wbk0bPP8DqXnK111fFnetr32cSBW749+LZDTYT1vF1hXt35z+gMNsbZLMsLV1+d6+jrYx5oiZPVC8EFng24VGlXudkBpKC/roHEBImu3EUhsoXTHE+3wpFm+sTGKG0toq/JJRqicZnwdPykImUzJmYrxxF+yECjwNtEVzGeTSQWDlD1xsW99tLqIntspVVUkxgs1qA3wA1yWAZCNu1JbYRImAUK62w/JZpl0PZFyBHPTG6frq80NdzYtE29K6W6RRLSyK5fx/kf6rYk9pPvM=
      app: ufo-server
      on:
        repo: progremir/ufo-server